"""0001_init_schema

Revision ID: 006c3ef9c10d
Revises: 
Create Date: 2026-06-15 10:46:34.960904

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.models.types import EncryptedString

# revision identifiers, used by Alembic.
revision: str = '006c3ef9c10d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # PostgreSQL 扩展：citext（大小写不敏感 email）+ pg_trgm（相似度搜索，预留）
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('async_jobs',
    sa.Column('task_type', postgresql.ENUM('parse', 'extract', 'screen', 'score', 'email_fetch', 'export', name='async_job_type'), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('status', postgresql.ENUM('queued', 'running', 'success', 'failed', 'retry', name='async_job_status'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_async_jobs_idempotency_key'), 'async_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_async_jobs_status'), 'async_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_async_jobs_target_id'), 'async_jobs', ['target_id'], unique=False)
    op.create_index(op.f('ix_async_jobs_task_type'), 'async_jobs', ['task_type'], unique=False)
    op.create_table('teams',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('dedup_key', sa.String(), nullable=False),
    sa.Column('name', EncryptedString(), nullable=False),
    sa.Column('phone', EncryptedString(), nullable=True),
    sa.Column('email', EncryptedString(), nullable=True),
    sa.Column('merged_into', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_dedup_key'), 'candidates', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_candidates_email'), 'candidates', ['email'], unique=False)
    op.create_index(op.f('ix_candidates_team_id'), 'candidates', ['team_id'], unique=False)
    op.create_table('email_configs',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('imap_host', sa.String(), nullable=False),
    sa.Column('imap_port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_enc', EncryptedString(), nullable=False),
    sa.Column('poll_interval_min', sa.Integer(), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id')
    )
    op.create_table('llm_calls',
    sa.Column('adapter', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('scope', postgresql.ENUM('extractor', 'scorer', 'reasoning', 'interview', name='llm_scope'), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_cny', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_llm_calls_adapter'), 'llm_calls', ['adapter'], unique=False)
    op.create_index(op.f('ix_llm_calls_called_at'), 'llm_calls', ['called_at'], unique=False)
    op.create_index(op.f('ix_llm_calls_scope'), 'llm_calls', ['scope'], unique=False)
    op.create_index(op.f('ix_llm_calls_team_id'), 'llm_calls', ['team_id'], unique=False)
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'member', name='user_role'), nullable=False),
    sa.Column('team_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index('uq_users_email_lower', 'users', [sa.text('lower(email)')], unique=True)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_table('candidate_sources',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('source_type', postgresql.ENUM('upload', 'platform', 'email', name='source_type'), nullable=False),
    sa.Column('source_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_sources_candidate_id'), 'candidate_sources', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_sources_source_type'), 'candidate_sources', ['source_type'], unique=False)
    op.create_table('dedup_matches',
    sa.Column('candidate_a', sa.UUID(), nullable=False),
    sa.Column('candidate_b', sa.UUID(), nullable=False),
    sa.Column('similarity', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'merged', 'rejected', name='dedup_match_status'), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_a'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_b'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dedup_matches_candidate_a'), 'dedup_matches', ['candidate_a'], unique=False)
    op.create_index(op.f('ix_dedup_matches_candidate_b'), 'dedup_matches', ['candidate_b'], unique=False)
    op.create_index(op.f('ix_dedup_matches_status'), 'dedup_matches', ['status'], unique=False)
    op.create_table('jobs',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('draft', 'active', 'closed', name='job_status'), nullable=False),
    sa.Column('llm_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_team_id'), 'jobs', ['team_id'], unique=False)
    op.create_table('candidate_resumes',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('file_storage_key', sa.String(), nullable=False),
    sa.Column('file_mime', sa.String(), nullable=True),
    sa.Column('parsed_text', sa.Text(), nullable=True),
    sa.Column('parse_status', postgresql.ENUM('pending', 'success', 'failed', 'low_text', name='parse_status'), nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['candidate_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_resumes_candidate_id'), 'candidate_resumes', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_resumes_parse_status'), 'candidate_resumes', ['parse_status'], unique=False)
    op.create_index(op.f('ix_candidate_resumes_source_id'), 'candidate_resumes', ['source_id'], unique=False)
    op.create_table('interview_questions',
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('dimension', postgresql.ENUM('skill', 'project', 'weakness', 'culture', name='interview_dimension'), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_batch_id'), 'interview_questions', ['batch_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_candidate_id'), 'interview_questions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_interview_questions_job_id'), 'interview_questions', ['job_id'], unique=False)
    op.create_table('job_hard_requirements',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('min_education', postgresql.ENUM('high_school', 'bachelor', 'master', 'phd', name='education_level'), nullable=True),
    sa.Column('min_years', sa.Integer(), nullable=True),
    sa.Column('required_skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('excluded_companies', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('job_versions',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_versions_job_id'), 'job_versions', ['job_id'], unique=False)
    op.create_table('scores',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('skill', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=True),
    sa.Column('education', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Integer(), nullable=True),
    sa.Column('potential', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(), nullable=True),
    sa.Column('llm_call_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_score_job_candidate')
    )
    op.create_index(op.f('ix_scores_candidate_id'), 'scores', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_scores_job_id'), 'scores', ['job_id'], unique=False)
    op.create_table('screening_results',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('disqualified', sa.Boolean(), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('manually_overridden', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'candidate_id', name='uq_screening_job_candidate')
    )
    op.create_index(op.f('ix_screening_results_candidate_id'), 'screening_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_screening_results_job_id'), 'screening_results', ['job_id'], unique=False)
    op.create_table('interview_feedbacks',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_feedbacks_question_id'), 'interview_feedbacks', ['question_id'], unique=False)
    op.create_table('manual_overrides',
    sa.Column('screening_result_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['screening_result_id'], ['screening_results.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manual_overrides_screening_result_id'), 'manual_overrides', ['screening_result_id'], unique=False)
    op.create_table('parsed_structures',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('llm_call_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['llm_call_id'], ['llm_calls.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resume_id'], ['candidate_resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    op.create_table('score_reasons',
    sa.Column('score_id', sa.UUID(), nullable=False),
    sa.Column('type', postgresql.ENUM('recommend', 'disqualify', name='score_reason_type'), nullable=False),
    sa.Column('bullet_points', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['score_id'], ['scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_reasons_score_id'), 'score_reasons', ['score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_reasons_score_id'), table_name='score_reasons')
    op.drop_table('score_reasons')
    op.drop_table('parsed_structures')
    op.drop_index(op.f('ix_manual_overrides_screening_result_id'), table_name='manual_overrides')
    op.drop_table('manual_overrides')
    op.drop_index(op.f('ix_interview_feedbacks_question_id'), table_name='interview_feedbacks')
    op.drop_table('interview_feedbacks')
    op.drop_index(op.f('ix_screening_results_job_id'), table_name='screening_results')
    op.drop_index(op.f('ix_screening_results_candidate_id'), table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_index(op.f('ix_scores_job_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_candidate_id'), table_name='scores')
    op.drop_table('scores')
    op.drop_index(op.f('ix_job_versions_job_id'), table_name='job_versions')
    op.drop_table('job_versions')
    op.drop_table('job_hard_requirements')
    op.drop_index(op.f('ix_interview_questions_job_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_candidate_id'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_batch_id'), table_name='interview_questions')
    op.drop_table('interview_questions')
    op.drop_index(op.f('ix_candidate_resumes_source_id'), table_name='candidate_resumes')
    op.drop_index(op.f('ix_candidate_resumes_parse_status'), table_name='candidate_resumes')
    op.drop_index(op.f('ix_candidate_resumes_candidate_id'), table_name='candidate_resumes')
    op.drop_table('candidate_resumes')
    op.drop_index(op.f('ix_jobs_team_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_dedup_matches_status'), table_name='dedup_matches')
    op.drop_index(op.f('ix_dedup_matches_candidate_b'), table_name='dedup_matches')
    op.drop_index(op.f('ix_dedup_matches_candidate_a'), table_name='dedup_matches')
    op.drop_table('dedup_matches')
    op.drop_index(op.f('ix_candidate_sources_source_type'), table_name='candidate_sources')
    op.drop_index(op.f('ix_candidate_sources_candidate_id'), table_name='candidate_sources')
    op.drop_table('candidate_sources')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_llm_calls_team_id'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_scope'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_called_at'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_adapter'), table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_table('email_configs')
    op.drop_index(op.f('ix_candidates_team_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_dedup_key'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('teams')
    op.drop_index(op.f('ix_async_jobs_task_type'), table_name='async_jobs')
    op.drop_index(op.f('ix_async_jobs_target_id'), table_name='async_jobs')
    op.drop_index(op.f('ix_async_jobs_status'), table_name='async_jobs')
    op.drop_index(op.f('ix_async_jobs_idempotency_key'), table_name='async_jobs')
    op.drop_table('async_jobs')
    # ### end Alembic commands ###
